FROM docker.repo.local.sfdc.net/sfci/gec/devforce/sfdc_centos7_ruby_3_2_nodejs16:a79bb0924e13eac1d69b13ec11196b9384f9a351

# This includes 'vendor' and '.bundle' from the unit tests stage
COPY . /var/www/app

WORKDIR /var/www/app

ENV BUNDLE_PATH=/var/www/app/vendor/bundle \
    BUNDLE_APP_CONFIG=/var/www/app/bundle

ENV PORT=7442
ENV RAILS_ENV=production

CMD ["bash", "-e", "bin/server"]
EXPOSE 7442 15372
